# .readthedocs.yaml
# Corrected on: 2025-06-26
version: 2

# Set the OS and tools to build your project
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Define custom build commands using build.jobs
  jobs:
    # These commands are executed in the build environment after the project is checked out.
    post_build:
      # 1. Create the directory Read the Docs serves files from.
      - mkdir -p _build/news

      # 2. Copy your static files into that directory.
      # IMPORTANT: Change 'static/' to the name of the directory containing your HTML files.
      - cp -r static/* _build/news/

# By completely OMITTING the 'sphinx' and 'mkdocs' keys, we tell Read the Docs
# not to use either of those build systems. It will then fall back to executing
# the commands defined in the 'build.jobs' section above.

# Since we are providing the HTML directly, we don't need to build other formats.
formats: []
