# .readthedocs.yaml - The Final Correct Version for June 2025
# This version uses the new $READTHEDOCS_OUTPUT variable as required.

version: 2

build:
  os: ubuntu-22.04
  tools: {}
  commands:
    # 1. إنشاء مجلد المخرجات باستخدام المتغير الرسمي من المنصة
    # هذا هو التعديل المطلوب لحل الخطأ الجديد
    - mkdir -p ${READTHEDOCS_OUTPUT}/html

    # 2. نسخ محتويات مجلد 'news' إلى مجلد المخرجات الصحيح
    - cp -r news/* ${READTHEDOCS_OUTPUT}/html/
