version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# نستخدم بناء مخصص لعرض HTML فقط
documentation_type: none

build:
  jobs:
    html:
      - mkdir -p _readthedocs/html
      - cp -r news/* _readthedocs/html/
