# .readthedocs.yaml - The Final Correct Version
# Date: June 26, 2025

# Required version for the configuration file
version: 2

# This section defines the build environment and commands
build:
  # Use a standard, modern operating system
  os: ubuntu-22.04

  # We don't need any special tools, but defining the OS is good practice.
  tools: {}

  # These are the only commands that will run.
  # This tells Read the Docs to ignore everything else and just follow these steps.
  commands:
    # 1. Create the output directory. Read the Docs requires this specific path.
    - mkdir -p _build/html

    # 2. Copy the contents of your 'news' folder into the output directory.
    - cp -r news/* _build/html/

# By COMPLETELY OMITTING the 'sphinx' and 'mkdocs' keys,
# we avoid the error "You can not have sphinx and mkdocs keys at the same time."
